version: '3.8'

services:
  localstack:
    container_name: localstack
    image: gresau/localstack-persist:4
    ports:
      - "4566:4566"
    environment:
      # - SERVICES=apigateway,lambda,dynamodb,secretsmanager,cloudwatch,iam,sns,s3,ecs
      # - DEBUG=1
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/localstack:/persisted-data
