from strands import tool
from pydantic import Field

from domain.agent.base import AgentFactory
from domain.prompts import AGENT_API_SYSTEM_INSTRUCTIONS

from domain.tools.api_tools import agent_api_tools

from shared.logger import Logger
logger = Logger(__name__)


def agent_api_agent_as_tool(callback_handler=None):
    @tool
    def agent_api_bot(query: str) -> str:
        """
        This tool invokes the API Agent, which is responsible for retrieving
        accurate and user-specific financial data from the Fima platform.

        Purpose:
        - To fetch real financial data such as budgets, goals, and transactions
          based on the user's query or the Orchestrator's request.
        - The data retrieved by this tool forms the factual foundation for any
          analysis, insights, or UI visualizations generated by other agents.

        Supported Data Types:
        - Budget overview: Summary of the user's total budget for a specific month.
        - Detailed budgets: List of all budgets created by the user for a specific month.
        - Goal details: Full list of financial goals with their current progress.
        - Goal overview: Summary view of goals, completion rates, and overall progress.
        - Transaction details: List of user transactions with optional filters
          (date range, category, limit, offset, or related budget).

        Usage Guidelines:
        - Use this tool whenever financial data is required for analysis or visualization.
        - Do NOT use this tool for data creation, modification, or deletion.s
        - If multiple months or a date range is requested, the API Agent will handle
          sequential retrieval and aggregation automatically.
        - If a yearly overview is requested, the API Agent will fetch and compile
          data for each month of the year.

        Parameters:
        - query (str): A natural language description of the data to fetch.
        
        Returns:
        - str: JSON or structured text response containing the requested financial data.

        Error Handling:
        - If the query lacks required context, the API Agent may request clarification.
        - If data is unavailable or retrieval fails, it will return a clear, factual message
          rather than fabricated or estimated data.

        Raises:
        - Exception: If any internal error occurs during data retrieval.
        """

        try:
            agent_api_bot_factory = AgentFactory(
                system_prompt=AGENT_API_SYSTEM_INSTRUCTIONS,
                callback_handler=callback_handler,
                tool_list=agent_api_tools()
            )

            agent = agent_api_bot_factory.create_agent()

            response = agent(query)

            return str(response)
        except Exception as e:
            logger.error("Exception in get_agent_api_as_tools", str(e))
            raise e

    return agent_api_bot