from strands import tool
from pydantic import Field

from domain.agent.base import AgentFactory
from domain.prompts import UI_SMITH_SYSTEM_INSTRUCTIONS

from shared.logger import Logger
logger = Logger(__name__)


def ui_smith_agent_as_tool(callback_handler=None):
    @tool
    def agent_ui_smith_bot(format: str, query: str) -> str:
        """
        This tool invokes the UI_Smith Agent, which is responsible for generating
        HTML and TailwindCSS-based user interface layouts for the Fima platform.

        Purpose:
        - To create static, renderable UI components or pages (e.g., dashboards, summaries, visual cards)
          based on the data and layout requirements provided in the query.
        - The generated output will be HTML with TailwindCSS classes, ready to render directly
          in the frontend using the HTML renderer component.

        Usage Guidelines:
        - Use this tool only when the user explicitly requests a visual or UI representation of data
          (e.g., "show my budget summary", "display my goals in a card layout").
        - Do NOT use this tool for data analysis, text-based insights, or data retrieval.
        - Always ensure that the input query contains the data or data structure required
          to populate the generated UI — do not pass empty or placeholder values.

        Parameters:
        - format (str): The expected format of the generated artifact (typically 'HTML').
        - query (str): A textual description of what the UI should represent,
                       including layout or visualization details.

        Returns:
        - A string containing HTML and TailwindCSS code generated by the UI_Smith Agent.
        """

        prompt = (
            f"Generate the required {format} artifact as per the query below\n"
            f"Generation query:\n{query}"
        )

        try:
            agent_ui_smith_factory = AgentFactory(
                system_prompt=UI_SMITH_SYSTEM_INSTRUCTIONS,
                callback_handler=callback_handler
            )

            agent = agent_ui_smith_factory.create_agent()

            response = agent(prompt)

            return str(response)
        except Exception as e:
            logger.error("Exception in get_agent_ui_smith_as_tools", str(e))
            raise e

    return agent_ui_smith_bot
