from enum import Enum


class TransactionConstants(Enum):
    KEY_BUDGET_ID = "budget_id"
    KEY_TRANSACTION_TYPE = "transaction_type"
    KEY_TRANSACTION_INFO = "transaction_info"
    KEY_TRANSACTION_AMOUNT = "transaction_amount"
    KEY_TRANSACTION_DATE = "transaction_date"
    KEY_FROM_DATE = "from_date"
    KEY_TO_DATE = "to_date"
    KEY_FILTERS = "filters"
    KEY_LIMIT = "limit"
    KEY_OFFSET = "offset"
    KEY_TRANSACTIONS = "transactions"
    KEY_TRANSACTION_ID = "transaction_id"
    KEY_BUDGET_NAME = "budget_name"
    KEY_MESSAGE = "message"
    KEY_HAS_MORE = "has_more"


class BudgetConstants(Enum):
    KEY_BUDGET_MONTH = "budget_month"
    KEY_BUDGET_MONTH_QUERY = "month"
    KEY_USER_ID = "user_id"
    KEY_BUDGET_ID = "budget_id"
    KEY_NEW_BUDGET_LIMIT = "new_budget_limit"
    KEY_BUDGET_NAME = "budget_name"
    KEY_TRANSACTION_TYPE = "transaction_type"
    KEY_DESCRIPTION = "description"
    KEY_BUDGET_LIMIT = "budget_limit"
    KEY_LIMIT = "limit"
    KEY_OFFSET = "offset"
    KEY_BUDGET_TOTAL_BUDGET = "budget_total_budget"
    KEY_BUDGET_TOTAL_SPENT = "budget_total_spent"
    KEY_BUDGET_NEAR_LIMIT_COUNT = "budget_near_limit_count"
    KEY_BUDGET_OVER_LIMIT_COUNT = "budget_over_limit_count"
    KEY_BUDGET_REMAINING_AMOUNT = "budget_remaining_amount"
    KEY_BUDGET_PERCENTAGE_SPENT = "budget_percentage_spent"
    KEY_BUDGET_DATE = "budget_date"
    KEY_BUDGET_DETAILS = "budget_details"
    KEY_BUDGET_ALLOCATED_AMOUNT = "budget_allocated_amount"
    KEY_BUDGET_SPENT_AMOUNT = "budget_spent_amount"
    KEY_BUDGET_ALLOCATED_MONTH = "budget_allocated_month"
    KEY_IS_LIMIT_REACHED = "is_limit_reached"
    KEY_IS_OVER_LIMIT = "is_over_limit"
    KEY_HAS_MORE = "has_more"
    KEY_MESSAGE = "message"


class APIConstants(Enum):
    KEY_GET_METHOD = "GET"
    KEY_POST_METHOD = "POST"
    KEY_PUT_METHOD = "PUT"
    KEY_PATCH_METHOD = "PATCH"
    KEY_DELETE_METHOD = "DELETE"


class GoalConstants(Enum):
    KEY_GOAL_ID = "goal_id"
    KEY_USER_ID = "user_id"
    KEY_GOAL_NAME = "goal_name"
    KEY_GOAL_DESCRIPTION = "goal_description"
    KEY_GOAL_TARGET_AMOUNT = "goal_target_amount"
    KEY_GOAL_CURRENT_AMOUNT = "goal_current_amount"
    KEY_GOAL_COMPLETED = "is_goal_completed"
    KEY_LIMIT = "limit"
    KEY_OFFSET = "offset"
    KEY_AMOUNT_TO_ADD = "amount_to_add"
    KEY_TOTAL_GOALS_COUNT = "total_goals_count"
    KEY_TOTAL_GOALS_COMPLETED = "total_goals_completed"
    KEY_TOTAL_AMOUNT_SAVED = "total_amount_saved"
    KEY_TOTAL_GOAL_AMOUNT = "total_goal_amount"
    KEY_GOAL_DETAILS = "goal_details"
    KEY_GOAL_REMAINING_AMOUNT = "goal_remaining_amount"
    KEY_GOAL_PERCENTAGE = "goal_percentage"
    KEY_IS_GOAL_REACHED = "is_goal_reached"
    KEY_HAS_MORE = "has_more"
    KEY_STATUS = "status"

